ALTER TABLE "Lead" ADD COLUMN "phone" TEXT;
ALTER TABLE "Lead" ADD COLUMN "googleRating" REAL;
ALTER TABLE "Lead" ADD COLUMN "googleReviewCount" INTEGER;
ALTER TABLE "Lead" ADD COLUMN "icpFit" TEXT;
ALTER TABLE "Lead" ADD COLUMN "estimatedTicketValue" TEXT;
ALTER TABLE "Lead" ADD COLUMN "ownerLedProbability" TEXT;
ALTER TABLE "Lead" ADD COLUMN "singleLocation" BOOLEAN;
ALTER TABLE "Lead" ADD COLUMN "reviewStrength" TEXT;
ALTER TABLE "Lead" ADD COLUMN "websiteState" TEXT;
ALTER TABLE "Lead" ADD COLUMN "reachability" TEXT;
ALTER TABLE "Lead" ADD COLUMN "leadScore" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Lead" ADD COLUMN "priorityBucket" TEXT;
ALTER TABLE "Lead" ADD COLUMN "scoreExplanation" TEXT;
ALTER TABLE "Lead" ADD COLUMN "recommendedOffer" TEXT;
ALTER TABLE "Lead" ADD COLUMN "recommendedPriceBand" TEXT;
ALTER TABLE "Lead" ADD COLUMN "nextBestAction" TEXT;
ALTER TABLE "Lead" ADD COLUMN "qualificationNotes" TEXT;
ALTER TABLE "Lead" ADD COLUMN "qualificationUpdatedAt" DATETIME;
ALTER TABLE "Lead" ADD COLUMN "outreachChannelUsed" TEXT;
ALTER TABLE "Lead" ADD COLUMN "outreachOutcome" TEXT;
ALTER TABLE "Lead" ADD COLUMN "lostReason" TEXT;
ALTER TABLE "Lead" ADD COLUMN "meetingBooked" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Lead" ADD COLUMN "proposalSent" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Lead" ADD COLUMN "dealWon" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Lead" ADD COLUMN "dealValue" INTEGER;

CREATE INDEX "Lead_priorityBucket_leadScore_idx" ON "Lead"("priorityBucket", "leadScore");
CREATE INDEX "Lead_recommendedOffer_idx" ON "Lead"("recommendedOffer");
CREATE INDEX "Lead_websiteState_idx" ON "Lead"("websiteState");
